distinguer par type de case :

SELECT
    TRUNC(PURGE_DATE) AS PURGE_DAY,
    CASE_TYPE,
    COUNT(*) AS NB_CASES_PURGEES
FROM BCP_RETENTION_CASE
WHERE PURGE_STATUS = 'PURGED'
  AND PURGE_DATE IS NOT NULL
GROUP BY
    TRUNC(PURGE_DATE),
    CASE_TYPE
ORDER BY
    PURGE_DAY DESC,
    CASE_TYPE;

Et par pays :

SELECT
    TRUNC(rc.PURGE_DATE) AS PURGE_DAY,
    c.CODE AS COUNTRY,
    COUNT(*) AS NB_CASES_PURGEES
FROM BCP_RETENTION_CASE rc
JOIN BCP_COUNTRY c
    ON c.ID = rc.COUNTRY_ID
WHERE rc.PURGE_STATUS = 'PURGED'
  AND rc.PURGE_DATE IS NOT NULL
GROUP BY
    TRUNC(rc.PURGE_DATE),
    c.CODE
ORDER BY
    PURGE_DAY DESC,
    c.CODE;
